from typing import Any

class AstrbotOrchestrator:
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
    def register_star(self, name: str, handler: str) -> None: ...
    def unregister_star(self, name: str) -> None: ...
    def list_stars(self) -> list[str]: ...
    def record_activity(self) -> None: ...
    def get_stats(self) -> dict[str, Any]: ...
    def set_protocol_connected(self, protocol: str, connected: bool) -> None: ...
    def get_protocol_status(self, protocol: str) -> dict[str, Any] | None: ...

def get_orchestrator() -> AstrbotOrchestrator: ...
def cli() -> None: ...
